server:
  port: 8762
eureka:
  instance:
    hostname: eureka-server-2 #eureka.instance.hostname不能重复，否则集群失败，所以不能为localhost或者ip地址
  client:
    service-url:
      defaultZone: http://eureka-server-1:8761/eureka   #设置Eureka Server的交互地址
    register-with-eureka: false #是否要注册到其他Server上
    fetch-registry: false       #是否拉取服务信息
spring:
  application:
    name: sc-eureka-server  # 两个集群项目的spring.application.name必须相同，eureka.instance.hostname必须不同，否则都会失败。（至少我测试的是这样）
security:
  basic:
    enabled: true #开启基于HTTP用户认证
  user:
    name: admin   #登录账号
    password: admin   #登录密码

