server:
  port: 8889
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: INFO
    mysql: INFO
spring:
  application:
    name: sc-server-consumer
eureka:
  instance:
    prefer-ip-address: true
