server:
  port: 8889
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: INFO
    mysql: INFO
spring:
  application:
    name: sc-server-consumer
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      # 注册到eureka集群
      # defaultZone: http://eureka-server-1:8761/eureka/,http://eureka-server-2:8762/eureka/
      # 注册到带有用户认证的eureka
      defaultZone: http://admin:admin@eureka-server-1:8761/eureka/,http://admin:admin@eureka-server-2:8762/eureka/
